# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SATDBailiff CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Test SATDBailiff Runs
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install javajfx
      run: |
        wget https://download2.gluonhq.com/openjfx/11.0.2/openjfx-11.0.2_linux-x64_bin-sdk.zip
        sudo apt-get install unzip
        unzip openjfx-11.0.2_linux-x64_bin-sdk.zip -d openjfx-11.0.2
        cd openjfx-11.0.2
        sudo cp -arf lib/ ${JAVA_HOME}/lib/
    - name: Acquiring Satd Detector
      run: |
        sudo mkdir lib
        sudo chmod +x ./lib
        sudo wget -N https://github.com/Tbabm/SATDDetector-Core/releases/download/v0.1/satd_detector.jar 
        sudo mv satd_detector.jar /home/runner/work/SATDBailiff/SATDBailiff/lib
    - name: Build tool
      run: mvn -B package --file pom.xml
